/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tcl.librory.gui;

import com.tcl.librory.database.dao.BookDao;
import com.tcl.librory.database.dao.impl.BookDaoImpl;
import com.tcl.librory.models.Book;
import com.tcl.librory.models.Genre;
import java.io.IOException;
import java.util.EnumSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author benjo.uriarte
 */
public class BookAdd extends javax.swing.JFrame {

    private BookDao bookDao;
    private Book book;
    /**
     * Creates new form AddBook
     */
    public BookAdd(Book book) {
        initComponents();
	this.book = book;
        prepareFields();
	try {
	    bookDao = new BookDaoImpl();
	} catch (IOException ex) {
	    Logger.getLogger(BookAdd.class.getName()).log(Level.SEVERE, null, ex);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        controlNumberL = new javax.swing.JLabel();
        titleL = new javax.swing.JLabel();
        authorL = new javax.swing.JLabel();
        purchaseDateL = new javax.swing.JLabel();
        publisherL = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtPublisher = new javax.swing.JTextField();
        txtPublishedDate = new javax.swing.JTextField();
        controlNumberL2 = new javax.swing.JLabel();
        controlNumberL3 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        txtControlNumber = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        cbxGenre = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        controlNumberL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        controlNumberL.setText("Control Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(controlNumberL, gridBagConstraints);

        titleL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleL.setText("Title:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(titleL, gridBagConstraints);

        authorL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        authorL.setText("Author:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(authorL, gridBagConstraints);

        purchaseDateL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        purchaseDateL.setText("Published Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(purchaseDateL, gridBagConstraints);

        publisherL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        publisherL.setText("Publisher:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(publisherL, gridBagConstraints);

        txtTitle.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(txtTitle, gridBagConstraints);

        txtAuthor.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(txtAuthor, gridBagConstraints);

        txtPublisher.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(txtPublisher, gridBagConstraints);

        txtPublishedDate.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(txtPublishedDate, gridBagConstraints);

        controlNumberL2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        controlNumberL2.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(controlNumberL2, gridBagConstraints);

        controlNumberL3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        controlNumberL3.setText("Genre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(controlNumberL3, gridBagConstraints);

        txtIsbn.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(txtIsbn, gridBagConstraints);

        txtControlNumber.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(txtControlNumber, gridBagConstraints);

        add.setText("Submit");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonSubmit(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 7, 3);
        getContentPane().add(add, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 1);
        getContentPane().add(cbxGenre, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onButtonSubmit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonSubmit
	String controlNumber = txtControlNumber.getText().trim();
	String title = txtTitle.getText().trim();
	String author = txtAuthor.getText().trim();
	String publisher = txtAuthor.getText().trim();
	String publishedDate = txtPublishedDate.getText().trim();
	String isbn = txtIsbn.getText().trim();
	if (StringUtils.isNotEmpty(controlNumber) && StringUtils.isNotEmpty(title)) {
	    Book book = new Book();
	    book.setControlNumber(Long.valueOf(controlNumber));
	    book.setTitle(title);
	    book.setAuthor(author);
	    book.setPublisher(publisher);
	    book.setIsbn(isbn);
	}
    }//GEN-LAST:event_onButtonSubmit

    private void prepareFields() {
        cbxGenre.setModel(new DefaultComboBoxModel<>(Genre.values()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel authorL;
    private javax.swing.JComboBox<Genre> cbxGenre;
    private javax.swing.JLabel controlNumberL;
    private javax.swing.JLabel controlNumberL2;
    private javax.swing.JLabel controlNumberL3;
    private javax.swing.JLabel publisherL;
    private javax.swing.JLabel purchaseDateL;
    private javax.swing.JLabel titleL;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtControlNumber;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPublishedDate;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
